#!/usr/bin/env python3
"""Generate the research-impact block of index.html from data/metrics.json.

Deliberately chart-free. An earlier version drew three SVG charts here; they were
removed on 2026-08-10 because two of them put small numbers on screen — a
publications-per-year chart topping out at 5, and a repo table showing single-digit
star and fork counts. A weak number rendered large is worse than no chart. What is
left is the set of figures that are genuinely strong, as plain stat tiles.

Rule for anything added back here: if a number would not impress a senior hiring
manager on its own, it does not get a tile, and it certainly does not get an axis.

Usage:
    python3 tools/build_charts.py            # inject into index.html
    python3 tools/build_charts.py --check    # fail if index.html is out of date

Data source: data/metrics.json, which mirrors db/profile/scholar.json in the brain
repo. Re-verify the numbers there before regenerating.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "metrics.json"
INDEX = ROOT / "index.html"

START = "<!-- IMPACT:START — generated by tools/build_charts.py, do not edit by hand -->"
END = "<!-- IMPACT:END -->"


def tile(value: object, key: str, sub: str) -> str:
    return (
        f'<div class="stat"><span class="stat-v">{value}</span>'
        f'<span class="stat-k">{key}</span><span class="stat-sub">{sub}</span></div>'
    )


def stat_tiles(m: dict) -> str:
    k = m["metrics"]
    cites = {y: n for y, n in m["citationsByYear"].items() if not y.startswith("_")}
    oss = m["openSource"]["totals"]
    eu = m["euHorizon"]

    tiles = [
        (k["citationsAll"], "citations", f'{k["citationsSince2021"]} of them since 2021'),
        (k["hIndexAll"], "h-index", f'i10-index {k["i10All"]}'),
        (k["peerReviewedPublished"], "peer-reviewed papers", f'{k["underReviewOrInPreparation"]} more under review or in preparation'),
        (cites["2025"], "citations in 2025", f'up from {cites["2024"]} in 2024; {cites["2026"]} more by Aug 2026'),
        (eu["projects"], "EU Horizon projects", f'{eu["led"]} of them led'),
        (oss["pypiReleases"], "package releases", f'across {oss["pypiPackages"]} packages on PyPI'),
        (oss["commits"], "commits", "across the five flagship repositories"),
        (oss["externalContributors"], "outside contributors", "have landed changes in the repos"),
    ]
    return '      <div class="stat-row">' + "".join(tile(*t) for t in tiles) + "</div>"


def render(m: dict) -> str:
    return f"""{START}
  <section id="impact" class="panel-section alt">
    <div class="container">
      <p class="section-eyebrow">// impact &nbsp;—&nbsp; verified {m['_verifiedOn']}</p>
      <h2 class="section-title">The work is cited, and the citations are accelerating.</h2>
      <p class="section-lead">
        More citations arrived in the twenty months from January&nbsp;2025 than in the preceding
        eighteen years combined. Every figure below is read from a primary source — Google&nbsp;Scholar,
        Crossref, the GitHub API, PyPI — and kept in
        <a href="data/metrics.json">a single JSON file</a> that generates this block. Nothing here is
        typed by hand.
      </p>

{stat_tiles(m)}

      <p class="chart-source">
        Sources: <a href="{m['identity']['scholarUrl']}" target="_blank" rel="noopener">Google&nbsp;Scholar</a>,
        <a href="https://orcid.org/{m['identity']['orcid']}" target="_blank" rel="noopener">ORCID</a>,
        <a href="https://openalex.org/{m['identity']['openalexId']}" target="_blank" rel="noopener">OpenAlex</a>,
        Crossref, the GitHub API and PyPI — all read on {m['_verifiedOn']}.
        The full publication list, with DOIs and BibTeX, is on the
        <a href="publications/">publications page</a>; the open datasets behind the research are on the
        <a href="datasets/">datasets page</a>.
      </p>
    </div>
  </section>
  {END}"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if index.html is stale")
    args = parser.parse_args()

    metrics = json.loads(DATA.read_text(encoding="utf-8"))
    block = render(metrics)
    html = INDEX.read_text(encoding="utf-8")

    if START not in html or END not in html:
        print(f"error: {INDEX} is missing the {START!r} / {END!r} markers", file=sys.stderr)
        return 2

    head, rest = html.split(START, 1)
    _, tail = rest.split(END, 1)
    updated = head + block + tail

    if args.check:
        if updated != html:
            print("index.html is out of date — run: python3 tools/build_charts.py", file=sys.stderr)
            return 1
        print("index.html is up to date")
        return 0

    if updated == html:
        print("index.html already up to date")
        return 0
    INDEX.write_text(updated, encoding="utf-8")
    print(f"injected the impact section into {INDEX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
