#!/usr/bin/env python3
"""Self-host the web fonts instead of hotlinking Google Fonts.

Why this exists (two independent reasons, both real):

1. Performance. Hotlinking put a *third-party, render-blocking* stylesheet in
   the critical path of every page: the browser had to resolve DNS + TLS to
   fonts.googleapis.com, fetch 17 KB of CSS, and only *then* learn the font URLs
   and start a second DNS + TLS to fonts.gstatic.com. Two extra handshakes
   before a single glyph could download. Self-hosted, the fonts sit on the same
   origin as the page and are already connected.

2. GDPR. Hotlinked Google Fonts transmit the visitor's IP to Google. LG Munchen I
   (20 Jan 2022, Az. 3 O 17493/20) held that doing so without consent violates
   the GDPR and awarded damages. This site is run from the EU and sells services
   to EU clients from /hire/, so that is a live exposure, not a theoretical one.

Run from the site root:  python3 tools/selfhost_fonts.py
Idempotent: re-running re-downloads and rewrites, and skips already-patched HTML.
"""
import os, re, sys, pathlib, urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTDIR = ROOT / "assets" / "fonts"
CSS_OUT = FONTDIR / "fonts.css"

# The union of every family/weight any page asks for (404.html asks for a subset).
GF_URL = ("https://fonts.googleapis.com/css2"
          "?family=Space+Grotesk:wght@500;600;700"
          "&family=IBM+Plex+Sans:wght@400;500;600"
          "&family=IBM+Plex+Mono:wght@400;500;600"
          "&display=swap")

# Keep latin and latin-ext only. unicode-range means a browser downloads a file
# ONLY if the page actually needs a glyph from that range, so shipping latin-ext
# costs nothing at runtime but keeps accented names in the bibliography correct.
KEEP = {"latin", "latin-ext"}

# woff2 is only offered to a modern UA; with a bare UA Google serves legacy ttf.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def main():
    FONTDIR.mkdir(parents=True, exist_ok=True)
    css = fetch(GF_URL)

    blocks = re.findall(r"/\*\s*([a-z0-9\-\[\]]+)\s*\*/\s*@font-face\s*\{(.*?)\}", css, re.S)
    if not blocks:
        sys.exit("could not parse the Google Fonts CSS — aborting rather than "
                 "writing a broken stylesheet")

    out, kept, total = [], 0, 0
    out.append("/* Self-hosted web fonts — generated by tools/selfhost_fonts.py.\n"
               "   Do not edit by hand; re-run the script instead.\n"
               "   Replaces a render-blocking third-party request to Google Fonts\n"
               "   (also a GDPR exposure: it leaked visitor IPs to Google). */\n")

    for subset, body in blocks:
        if subset not in KEEP:
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", body)
        wt = re.search(r"font-weight:\s*(\d+)", body)
        sty = re.search(r"font-style:\s*(\w+)", body)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", body)
        rng = re.search(r"unicode-range:\s*([^;]+);", body)
        if not (fam and wt and url):
            continue

        fname = f"{fam.group(1).replace(' ', '-').lower()}-{wt.group(1)}-{subset}.woff2"
        dest = FONTDIR / fname
        data = fetch(url.group(1), binary=True)
        dest.write_bytes(data)
        kept += 1
        total += len(data)

        out.append("@font-face {")
        out.append(f"  font-family: '{fam.group(1)}';")
        out.append(f"  font-style: {sty.group(1) if sty else 'normal'};")
        out.append(f"  font-weight: {wt.group(1)};")
        # swap: show text immediately in the fallback, restore when the font lands.
        # Without it the browser blocks text for up to 3s (a bare LCP regression).
        out.append("  font-display: swap;")
        out.append(f"  src: url('/assets/fonts/{fname}') format('woff2');")
        if rng:
            out.append(f"  unicode-range: {rng.group(1).strip()};")
        out.append("}")

    CSS_OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {kept} woff2 files ({total/1024:.0f} KB) + {CSS_OUT.relative_to(ROOT)}")

    # --- patch every page off Google Fonts and onto the local stylesheet -------
    gf_link = re.compile(r'[ \t]*<link[^>]+fonts\.googleapis\.com[^>]*>\s*\n?', re.I)
    preconnect = re.compile(r'[ \t]*<link[^>]+rel="preconnect"[^>]+fonts\.(googleapis|gstatic)\.com[^>]*>\s*\n?', re.I)

    # Preload only what paints first: the display face used by the H1 and the
    # body regular. Preloading all nine would contend with the HTML itself.
    preloads = (
        '  <link rel="preload" href="/assets/fonts/space-grotesk-600-latin.woff2" as="font" type="font/woff2" crossorigin />\n'
        '  <link rel="preload" href="/assets/fonts/ibm-plex-sans-400-latin.woff2" as="font" type="font/woff2" crossorigin />\n'
    )
    local = '  <link rel="stylesheet" href="/assets/fonts/fonts.css" />\n'

    patched = 0
    for html in sorted(ROOT.rglob("*.html")):
        if ".git" in html.parts:
            continue
        s = html.read_text(encoding="utf-8")
        if "fonts.googleapis.com" not in s:
            continue
        s = preconnect.sub("", s)
        s = gf_link.sub(preloads + local, s, count=1)
        s = gf_link.sub("", s)          # any stragglers
        html.write_text(s, encoding="utf-8")
        patched += 1
        print(f"  patched {html.relative_to(ROOT)}")
    print(f"patched {patched} HTML files")


if __name__ == "__main__":
    main()
